config/routes.rb
WineReview::Application.routes.draw do
  resources :wines do
    resources :log_entries
    get 'page/:page', :action => :index, :on => :collection
  end
  root 'wines#index'

end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
  RATINGS = 1..5
  belongs_to :wine
    validates :name, :rating, :location, :comments, :tasted_on, presence: true
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  VARIETALS = ['Chardonnay', 'Cabernet Sauvignon', 'Merlot']
 
  has_many :log_entries, dependent: :destroy
  validates :name, :year, :country, presence: true
  validates :varietal, :inclusion => { :in => VARIETALS }
  validates :year,
	   numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  
  def average_rating
    if log_entries.loaded?
      log_entries.map(&:rating).compact.average
    else
      log_entries.average(:rating)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
	before_action :set_wine

	def index
	  @log_entries = @wine.log_entries.order('created_at desc')
	end

	def new
	  @log_entry = @wine.log_entries.new
	end

	def create
	  @log_entry = @wine.log_entries.new(log_entry_params)
	  if @log_entry.save
	    redirect_to wine_log_entries_path(@wine), notice: 'Log Entry saved!'
	  else
	    render :new
	  end
	end

	private

	def set_wine
	  @wine = Wine.find(params[:wine_id])
	end

	private

	def  log_entry_params
	  params.require(:log_entry).permit(:name, :rating, :location, :comments, :tasted_on)
	end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [ :show, :edit, :update, :destroy ]
    
  def index
    @available_at = Time.now
    @wines = Wine.order(:name).page(params[:page])
  end

  def show
  end

  def new
  	@wine = Wine.new
  end

  def create
  	@wine = Wine.new(wine_params)
    if @wine.save
      redirect_to @wine, notice: "#{@wine.name} was created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
  	if @wine.update(wine_params)
  	 redirect_to @wine, notice: "#{@wine.name} was updated!"
    else
      render :new
    end
  end

  def destroy
  	@wine.destroy
    redirect_to wines_url
  end

  def set_wine
    @wine = Wine.find(params[:id])
  end

  def wine_params
      params.require(:wine).permit(:name, :year, :winery, :country, :varietal)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
	def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
  end

  def formatted_date(time)
    time.strftime("%B %d, %Y")
  end

  def format_average_rating(wine)
    average = wine.average_rating
    if average
      pluralize(number_with_precision(average, precision: 1), 'rating')
    else
      'No reviews'
    end
  end
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Wine Review', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Navigation</h3>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to 'All Wines', wines_path %>
    </p>
    <p>
      <%= link_to 'Create Wine', new_wine_path %>
    </p>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wine Review <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/log_entries/_form.html.erb
<%= form_for( [ @wine, @log_entry ] ) do |f| %>
  <%= render 'shared/validation_errors', object: @log_entry %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: 'Name' %><br />
  <% f.label :rating %>  
  <% LogEntry::RATINGS.each do |rating| %>
    <%= f.radio_button :rating, rating %> <%= rating %>
  <% end %><br />
  <%= f.label :location %>
  <%= f.text_field :location, placeholder: 'Location' %><br />
  <%= f.label :comments %><br/>
  <%= f.text_area :comments %><br/>
  <%= f.label :tasted_on %> <%= f.date_select(:tasted_on) %>
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wine_log_entries_path(@wine), id: 'cancel_log_entry' %>
  </p>
<% end %>

app/views/log_entries/index.html.erb
<header>Log Entries for <%= link_to(@wine.name, @wine) %></header>
<ol id="log_entries">
  <% @log_entries.each do |log_entry| %>
    <li>
      <span class="rating"><%= pluralize(log_entry.rating, 'star') %></span>
      <span class="user">by <%= log_entry.name %> </span>
      <span class="date">
        <%= time_ago_in_words(log_entry.created_at) %> ago
      </span>
      <span class="location">in <%= log_entry.location %> </span>
      <span class="date">, tasted on: <%= formatted_date(log_entry.tasted_on) %> </span>
      <p>
        &quot;<%= log_entry.comments %>&quot;
      </p>
    </li>
  <% end %>
</ol>
<%= link_to 'Enter a Log Entry', new_wine_log_entry_path(@wine),
        remote: true,
        data: { 'update-target' => 'log_entry_form_container' },
        class: 'btn btn-primary' %>

<div id="log_entry_form_container"></div>

app/views/log_entries/new.html.erb
<h1>Write a log entry for <%= @wine.name %></h1>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <%= render 'shared/validation_errors', object: @wine %>
  <%= f.label :name %> <%= f.text_field :name, autofocus: true %><br />
  <%= f.label :year %> <%= f.text_field :year %><br />
  <%= f.label :winery %> <%= f.text_field :winery %><br />
  <%= f.label :country %> <%= f.text_field :country %><br />
  <%= f.label :varietal %> <%= f.select :varietal, Wine::VARIETALS, { prompt: "Pick one" } %>

  <br />
  <p>
    <%= f.submit %> 
    <%= link_to 'Cancel', wines_path %>
  </p>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine <%= @wine.name %></h1>
<%= render 'form' %>

app/views/wines/index.html.erb
<h1>Wines</h1>
<p>Available as <%= formatted_time(@available_at) %></p>
<%= page_entries_info @wines %>
<ol>
<% @wines.each do |wine| %>
  <li><%= link_to(wine.name, wine) %> a <%= wine.varietal %> from <%= wine.winery %> </li>
<% end %>
</ol>
<%= paginate @wines %>

app/views/wines/new.html.erb
<h1>Creating a new Wine</h1>
<%= render 'form' %>

app/views/wines/show.html.erb
<% content_for :name, @wine.name %>
<article class="wine">
  <header>
    <h2><%= @wine.name %></h2>
  </header>
  <p><label>Year:</label> <%= @wine.year %></p>
  <p><label>Winery:</label> <%= @wine.winery %></p>
  <p><label>Country:</label> <%= @wine.country %></p>
  <p><label>Varietal:</label> <%= @wine.varietal %></p>
  <p><label>Average Review:</label> <%= format_average_rating(@wine) %></p>
</article>

<p>
  Read all
  <%= link_to pluralize(@wine.log_entries.size, 'Log Entry'), wine_log_entries_path(@wine) %>
</p>

<%= link_to 'All Wine', wines_path %> 
| <%= link_to 'Edit', edit_wine_path(@wine) %>
  
<%= button_to 'Delete', @wine,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>